123 play hitsound on hit
maxrchung/S2VX pull request #156
Opened 2020-09-26 20:19 UTC by maxrchung

- Hit sound plays for editor note when it is expected to be played. I have some simple flagging logic that prevents duplicate sounds from being played.
- Play mode note click triggers a miss sound. This is temporary. I figure whoever's doing more of the logic with note clicking or score tracking can set this up more appropriately.
- I reworked Volume so that it sets the global Volume instead of just for Track. I'm hooking onto osu's default configuration system, so you should see your volume changes automatically saved inside of a file similar to this one: C:\Users\Wax Chug da Gwad\AppData\Roaming\S2VX\framework.ini

2020-09-27 01:09 UTC, Naranja-Sagged approved these changes

2020-10-02 03:48 UTC, Xenocidel commented
Starting Play in the middle of the song after some notes registers them as misses and plays the miss sound for each.

2020-10-02 08:22 UTC, maxrchung commented
> Starting Play in the middle of the song after some notes registers them as misses and plays the miss sound for each.

This is because Delete() is being called in the Update() function for each GameNote. I'll look into this and maybe provide a fix.

2020-10-02 08:58 UTC, maxrchung commented
I fixed this by explicitly removing some notes from Story before it starts playing. This prevents hitsounds from being played and, another issue that would have come up, score from being calculated.

2020-10-02 20:21 UTC, Xenocidel requested changes

2020-10-02 20:21 UTC, Xenocidel commented on S2VX.Game/Story/S2VXStory.cs
> +            while (Notes.Children.Count > 0 && Notes.Children.First().EndTime < trackTime) {
I still see the issue of notes being counted as Misses in the case where you still have notes after trackTime. I breakpointed and investigated Notes.Children(). They are not ordered by EndTime, seems like they are arbitrarily ordered.

2020-10-05 00:20 UTC, Xenocidel approved these changes

2020-10-05 03:03 UTC, merged